[package]
name = "tauri"
version = "1.0.0-beta-rc.1"
authors = [ "Tauri Programme within The Commons Conservancy" ]
categories = [ "gui", "web-programming" ]
license = "Apache-2.0 OR MIT"
homepage = "https://tauri.studio"
repository = "https://github.com/tauri-apps/tauri"
description = "Make tiny, secure apps for all desktop platforms with Tauri"
edition = "2018"
exclude = [ "test/fixture/**" ]

[package.metadata.docs.rs]
features = [ "api-all" ]

[dependencies]
serde_json = { version = "1.0", features = [ "raw_value" ] }
serde = { version = "1.0", features = [ "derive" ] }
base64 = "0.13.0"
tokio = { version = "1.4", features = [ "rt", "rt-multi-thread", "sync" ] }
futures = "0.3"
uuid = { version = "0.8.2", features = [ "v4" ] }
thiserror = "1.0.24"
once_cell = "1.7.2"
tauri-macros = { version = "1.0.0-beta-rc.0", path = "../tauri-macros" }
tauri-utils = { version = "1.0.0-beta-rc.0", path = "../tauri-utils" }
wry = "0.8"
rand = "0.8"
reqwest = { version = "0.11", features = [ "json", "multipart" ] }
tempfile = "3"
semver = "0.11"
serde_repr = "0.1"
dirs-next = "2.0.0"
zip = "0.5.11"
ignore = "^0.4.17"
either = "1.6.1"
tar = "0.4"
flate2 = "1.0"
rfd = "0.2.2"
tinyfiledialogs = "3.3"
bytes = { version = "1", features = [ "serde" ] }
http = "0.2"
clap = { version = "=3.0.0-beta.2", optional = true }
notify-rust = { version = "4.3.0", optional = true }
tauri-hotkey = { version = "0.1.0", optional = true }
open = "1.6.0"
shared_child = "0.3"
os_pipe = "0.9"
minisign-verify = "0.1.8"

[build-dependencies]
cfg_aliases = "0.1.1"

[dev-dependencies]
proptest = "1.0.0"
serde_json = "1.0"
tauri = { path = ".", features = [ "api-all" ] }
serde = { version = "1.0", features = [ "derive" ] }
quickcheck = "1.0.3"
quickcheck_macros = "1.0.0"
tokio-test = "0.4.1"
mockito = "0.29"

[features]
cli = [ "clap" ]
custom-protocol = [ "tauri-macros/custom-protocol" ]
api-all = [ "notification-all", "global-shortcut-all", "updater" ]
updater = [ "reqwest/default-tls" ]
fs-all = [ ]
fs-read-text-file = [ ]
fs-read-binary-file = [ ]
fs-write-file = [ ]
fs-write-binary-file = [ ]
fs-read-dir = [ ]
fs-copy-file = [ ]
fs-create-dir = [ ]
fs-remove-dir = [ ]
fs-remove-file = [ ]
fs-rename-file = [ ]
fs-path-api = [ ]
window-all = [ ]
window-create = [ ]
shell-all = [ ]
shell-execute = [ ]
shell-open = [ ]
dialog-all = [ ]
dialog-open = [ ]
dialog-save = [ ]
http-all = [ ]
http-request = [ ]
notification-all = [ "notify-rust" ]
global-shortcut-all = [ "tauri-hotkey" ]
